sudo: false
language: node_js

node_js:
  - "4.4"

before_script:
  - npm install -g eslint eslint-plugin-flow-vars babel-eslint eslint-plugin-standard eslint-plugin-promise flow-bin

script:
  - make check
  - make .move-in-node build-node .cleanup-node
  - make .move-in-browser build-browser .cleanup-browser
  - make .move-in-browser-extension build-browser-extension .cleanup-browser-extension
