sudo: required
language: node_js
dist: trusty

node_js:
  - "4.4"

before_script:
  - yarn

script:
  - make flow
  - make eslint
  - make build

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
